/**
 * PDF branding — JS module (no JSON import / MIME issues).
 * Logo is imported so Vite resolves a browser-ready URL for cover rendering.
 */

import logo from './assets/Teal Read Me Logo.png?url'

/** Public static URL (dev middleware + production copy of assets/). */
export const PDF_LOGO_PUBLIC_URL = '/modules/pdf-engine/assets/Teal%20Read%20Me%20Logo.png'

export const brandingConfig = {
  logo,
  logoFile: 'assets/Teal Read Me Logo.png',
  logoPlacement: 'top-center',
  logoWidth: 120,
  coverLogoWidth: 120,
  accentColor: '#008080',
  footerText: 'Generated by My Operating Manual',
  includeLogoOnCover: true,
  includeLogoOnFooter: false,
}

export default brandingConfig
