/**
 * DEPRECATED: Niche Graph Catalog (Money Maker)
 * 
 * This file was auto-generated by scripts/generate-niche-graphs.mjs
 * It contained references to 159+ niche-specific income and progress graphs.
 * 
 * It is NOT used by the My Operating Manual system.
 * The file has been disabled to prevent accidental use.
 * 
 * For Operating Manual PDF generation, the system uses inline SVG cockpit graphs only.
 * @see insertCockpitGraphs.js
 */

// ❌ DEPRECATED: This catalog is no longer used or maintained
// The graphs folder has been permanently removed.
// nicheGraphCatalog is kept as an empty object for reference only.

export const nicheGraphCatalog = {
  count: 0,
  byKey: {},
  note: 'DEPRECATED - Niche graphs removed as part of Money Maker cleanup'
};

export default nicheGraphCatalog;
